### PR TITLE
Tourlive 112 | UPDATE FROM MATSPORT

### PR DESCRIPTION
**Pull request by Hawner**

### CODE REVIEW

**Comment by ursforrer** [comment]
SonarQube analysis reported 8 issues

1. ![MAJOR][MAJOR] [UpdateController.java#L94](https://github.com/TourLive/api/blob/4d4c440ab62f04cc63388c866bbf46a214c678f4/app/controllers/UpdateController.java#L94): Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [UpdateController.java#L105](https://github.com/TourLive/api/blob/4d4c440ab62f04cc63388c866bbf46a214c678f4/app/controllers/UpdateController.java#L105): Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS00112)
1. ![MINOR][MINOR] [UpdateController.java#L97](https://github.com/TourLive/api/blob/4d4c440ab62f04cc63388c866bbf46a214c678f4/app/controllers/UpdateController.java#L97): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS135)
1. ![MINOR][MINOR] [UpdateController.java#L115](https://github.com/TourLive/api/blob/4d4c440ab62f04cc63388c866bbf46a214c678f4/app/controllers/UpdateController.java#L115): Use "Integer.parseInt" for this string-to-int conversion. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2130)
1. ![MINOR][MINOR] [UpdateController.java#L124](https://github.com/TourLive/api/blob/4d4c440ab62f04cc63388c866bbf46a214c678f4/app/controllers/UpdateController.java#L124): Add logic to this catch clause or eliminate it and rethrow the exception automatically. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2737)
1. ![MINOR][MINOR] [UpdateController.java#L134](https://github.com/TourLive/api/blob/4d4c440ab62f04cc63388c866bbf46a214c678f4/app/controllers/UpdateController.java#L134): Use "Integer.parseInt" for this string-to-int conversion. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2130)
1. ![MINOR][MINOR] [UpdateController.java#L135](https://github.com/TourLive/api/blob/4d4c440ab62f04cc63388c866bbf46a214c678f4/app/controllers/UpdateController.java#L135): Use "Integer.parseInt" for this string-to-int conversion. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2130)
1. ![MINOR][MINOR] [UpdateController.java#L141](https://github.com/TourLive/api/blob/4d4c440ab62f04cc63388c866bbf46a214c678f4/app/controllers/UpdateController.java#L141): Add logic to this catch clause or eliminate it and rethrow the exception automatically. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2737)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by ursforrer** [comment]
SonarQube analysis reported 1 issue

1. ![MINOR][MINOR] [UpdateController.java#L99](https://github.com/TourLive/api/blob/78289ad1d212de3af6417e1d12d2b9ebe8e9e507/app/controllers/UpdateController.java#L99): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS135)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Hawner** [comment]
stopped caring 20 commits ago!
Ignore this stupid sonarcloud issue .... due to logical performance .. what a *** tool 🥇

**Review by ursforrer — APPROVED** [review]
Well done 😜👍🏻

**Pull request merged**
